"""Explicitly SYNTHETIC herdr state for installed candidate scenarios.

Only screen observations/tab-create are live fixture replays; other responses
are scripted operation inputs, not purported captures or interactive safety proof.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from fr_dispatch.testing import run_item
from fr_herdr import managed, runner

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures/herdr"
PANE = "w1:p1"
NAME = "b-scenario"
MODEL = "openai/gpt-6.1-sol"


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, capture_output=True)


def prepare() -> managed.Descriptor:
    git(
        "-c",
        "user.name=scenario",
        "-c",
        "user.email=scenario@example.invalid",
        "commit",
        "--allow-empty",
        "-m",
        "fixture",
    )
    git("checkout", "-b", "feat/scenario")
    runs = Path("docs/superpowers/runs")
    runs.mkdir(parents=True)
    (runs / "scenario.yaml").write_text(
        "run: scenario\nbranch: feat/scenario\ncursor: deliver\n"
        "steps:\n  deliver:\n    state: done\n"
    )
    d = managed.Descriptor(
        server=managed.server_identity(),
        pane=PANE,
        name=NAME,
        item="example/alpha/run/batch-scenario",
        role="batch",
        branch="feat/scenario",
        checkout=str(Path.cwd()),
        model=MODEL,
    )
    managed.save(d)
    return d


def launch() -> None:
    prepare()
    linked = Path(os.environ["FR_HERDR_CACHE_DIR"]).parent / "linked"
    git("worktree", "add", "-b", "feat/linked", str(linked))
    calls = []

    def fake(args):
        calls.append(args)
        if args[:2] == ["tab", "create"]:
            return json.loads((FIXTURES / "tab-create.json").read_text())
        if args[:2] == ["agent", "list"]:
            return {
                "result": {
                    "agents": [
                        {
                            "pane_id": "w2:p1K",
                            "name": runner.agent_name(item.id),
                            "agent": "opencode",
                            "agent_status": "idle",
                            "interactive_ready": True,
                        }
                    ]
                }
            }
        if args[:2] == ["pane", "process-info"]:
            return {
                "result": {
                    "process_info": {
                        "foreground_processes": [
                            {
                                "pid": 2,
                                "argv": ["opencode", "--model", MODEL],
                                "cwd": str(Path.cwd()),
                            }
                        ]
                    }
                }
            }
        if args[:2] == ["pane", "read"]:
            return json.loads((FIXTURES / "opencode/final-idle.json").read_text())
        return {}

    runner._run_herdr = fake
    item = run_item(harness="opencode", model=MODEL, checkout=str(linked), branch="feat/scenario")
    handle = runner.HerdrRunner("w2").dispatch(item)
    assert handle == "w2:p1K"
    assert calls[0][calls[0].index("--cwd") + 1] == str(Path.cwd())
    assert ["--kind", "opencode"] == calls[1][3:5]
    assert calls[1][-3:] == ["--model", MODEL, "--auto"]
    assert "--wait" in next(c for c in calls if c[:2] == ["agent", "prompt"])
    assert managed.load(handle).item == item.id
    assert managed.load(handle).checkpoint == "active"
    d = managed.load(handle)
    assert "HOLD" in managed.reconstruct(d)
    # Explicitly synthetic live-conflict seam; brief generated by the real engine.
    from fr.triage.batch_dispatch import conflict_brief
    from fr.triage.model import Batch

    batch = Batch(id="scenario", title="scenario", ids=["alpha#1"])
    brief = conflict_brief(
        batch, pr=1, head="abc", paths=["file.py"], branch=d.branch, base="origin/main", mirrors=[]
    )
    current = managed.handback(d, brief)
    managed.conflict_current = lambda d: True
    assert "six steps" in managed.reconstruct(current)
    managed.conflict_current = lambda d: False
    assert "HOLD" in managed.reconstruct(current)

    def failed(args):
        if args[:2] == ["agent", "start"]:
            raise runner.HerdrError("synthetic startup failure")
        return fake(args)

    runner._run_herdr = failed
    try:
        runner.HerdrRunner("w2").dispatch(item)
    except runner.HerdrError:
        assert calls[-1][:2] == ["tab", "close"]
    else:
        raise AssertionError("failed startup was reported successful")


def herdr(args: list[str]) -> dict:
    state = Path(os.environ["HERDR_FAKE_STATE"])
    phase = state.read_text() if state.exists() else "source"
    with Path(os.environ["HERDR_FAKE_LOG"]).open("a") as log:
        log.write(json.dumps(args) + "\n")
    if args[:2] == ["agent", "list"]:
        return {
            "result": {
                "agents": [
                    {
                        "agent": "opencode",
                        "pane_id": PANE,
                        "tab_id": "w1:t1",
                        "name": NAME,
                        "agent_status": "done",
                        "interactive_ready": True,
                    }
                ]
            }
        }
    if args[:2] == ["tab", "list"]:
        return {
            "result": {"tabs": [{"tab_id": "w1:t1", "label": "example/alpha/run/batch-scenario"}]}
        }
    if args[:2] == ["pane", "read"]:
        return json.loads((FIXTURES / "opencode/final-idle.json").read_text())
    if args[:2] == ["pane", "process-info"]:
        proc = {"argv": ["opencode", "--model", MODEL], "pid": 2, "cwd": str(Path.cwd())}
        if phase == "shell":
            proc = {"argv": ["-zsh"], "pid": 1, "cwd": str(Path.cwd())}
        return {"result": {"process_info": {"shell_pid": 1, "foreground_processes": [proc]}}}
    if args[:2] == ["pane", "send-keys"]:
        state.write_text("shell")
    if args[:2] == ["agent", "start"]:
        assert args == [
            "agent",
            "start",
            NAME,
            "--kind",
            "opencode",
            "--pane",
            PANE,
            "--",
            "--model",
            MODEL,
            "--auto",
        ]
        state.write_text("target")
    return {}


if __name__ == "__main__":
    if sys.argv[1] == "scenario-launch":
        launch()
    elif sys.argv[1] == "scenario-prepare":
        prepare()
    else:
        print(json.dumps(herdr(sys.argv[1:])))
