#!/usr/bin/env python3
"""Generate index.html from slides.md + template.html.

slides.md is the source of truth for every word in the deck. This script
inlines it into index.html as `<script type="text/template">` blocks, one per
slide, so the deck stays a single self-contained file you can double-click --
reveal's external-markdown mode would need an HTTP server, because it fetches
the .md over XMLHttpRequest and browsers block that under file://.

The `<script>` wrapper is load-bearing, not decoration. Reveal's markdown
plugin reads `section.textContent` for an inline `data-markdown` slide. Put
raw HTML directly in the section and the browser has already parsed it into
elements, so textContent throws the markup away -- silently, at render time
only. Inside a `<script>` the same call returns the literal source, tags and
all, and marked passes the HTML through untouched.

Usage:
    uv run --no-project python build.py            # write index.html
    uv run --no-project python build.py --check    # exit 1 if index.html is stale

(`--no-project` because this script is pure stdlib and needs no venv sync.)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SLIDES_MD = HERE / "slides.md"
TEMPLATE = HERE / "template.html"
INDEX = HERE / "index.html"

BANNER = (
    "<!-- GENERATED by build.py from slides.md -- do not hand-edit.\n"
    "     Edit slides.md, then run: uv run --no-project python build.py -->"
)


def split_top_level(text: str, sep: str) -> list[str]:
    """Split on a `sep`-only line, ignoring separators inside fenced code."""
    parts: list[list[str]] = [[]]
    fenced = False
    for line in text.split("\n"):
        if line.lstrip().startswith("```"):
            fenced = not fenced
        if not fenced and line.strip() == sep:
            parts.append([])
            continue
        parts[-1].append(line)
    return ["\n".join(p).strip("\n") for p in parts]


def slide_label(body: str, n: int) -> str:
    """A readable `<!-- n title -->` marker for the generated file."""
    heading = re.search(r"^#{1,3} +(.+?)\s*$", body, re.M)
    title = heading.group(1) if heading else "slide"
    title = re.sub(r"[*`]", "", title)
    return f"<!-- {n} {title} -->"


class DeckError(Exception):
    """slides.md says something reveal would silently mangle."""


def check_slide(body: str, label: str) -> None:
    """Refuse a slide whose `Note:` is not last.

    Reveal's notes separator is greedy: everything after `Note:` becomes
    speaker notes. An `<img class="side">` placed after it -- legal in the
    HTML this deck was written in, where <aside> was a bounded element --
    gets swallowed into the note. The image then renders inside a collapsed
    <p>, and `img.side { width: 34% }` resolves to 34% of zero, so the
    portrait silently disappears. Catch it here instead.
    """
    lines = body.split("\n")
    note_at = next((i for i, line in enumerate(lines) if line.startswith("Note: ")), None)
    if note_at is None:
        return
    trailing = [line for line in lines[note_at + 1 :] if line.strip()]
    if trailing:
        raise DeckError(
            f"{label}: content follows the `Note:` line and would be swallowed "
            f"into the speaker notes -- move it above the note.\n"
            f"  offending line: {trailing[0][:70]}"
        )


def render_slide(body: str) -> str:
    return f'<section data-markdown>\n<script type="text/template">\n{body}\n</script>\n</section>'


def render_slides(markdown: str) -> str:
    out: list[str] = []
    for n, stack in enumerate(split_top_level(markdown, "---")):
        slides = split_top_level(stack, "--")
        for v, body in enumerate(slides):
            check_slide(body, f"slide {n}" if len(slides) == 1 else f"slide {n}/{v}")
        out.append(slide_label(slides[0], n))
        if len(slides) == 1:
            out.append(render_slide(slides[0]))
        else:
            out.append("<section>")
            out.extend(render_slide(s) for s in slides)
            out.append("</section>")
        out.append("")
    return "\n".join(out).strip("\n")


def render(markdown: str | None = None, template: str | None = None) -> str:
    markdown = SLIDES_MD.read_text() if markdown is None else markdown
    template = TEMPLATE.read_text() if template is None else template
    return template.replace("<!-- SLIDES -->", f"{BANNER}\n\n{render_slides(markdown)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify index.html matches slides.md instead of writing it",
    )
    args = ap.parse_args()

    built = render()
    if args.check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != built:
            print(
                f"{INDEX.name} is stale with respect to {SLIDES_MD.name}.\n"
                f"Run: uv run --no-project python {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        print(f"{INDEX.name} is up to date.")
        return 0

    INDEX.write_text(built)
    slides = built.count('<script type="text/template">')
    print(f"wrote {INDEX.name} ({slides} slides) from {SLIDES_MD.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
