"""The agents fr renders into a repo, the `agents` artifact kind (cloud-triage R19, §H).

A Claude Code cloud session loads its agent types before its setup script runs, so the
plugin's `super-fr:` agents are not dispatchable there; the same agents committed under
the repo's `.claude/agents/` are, from the first turn. So fr renders its two dispatched
agents into the repo: the canonical `plugins/super-fr/agents/<name>.md` with one added
front-matter key, `fr_artifact_version`, the stamp.

The canonical text ships here as package data (`fr/agents/<name>.md`, generated by
`scripts/sync-agents-data.py`), read through `importlib.resources` so every harness's
`fr` can render it. `CANONICAL_SHA256` pins that text at `PINNED_AT_VERSION`: a change to
either agent fails `tests/unit/test_tripwire_agents_data.py` until the kind's
`current_version` moves with it, which is what makes every repo's copy stale (and its
CI red) until `fr migrate artifacts --yes` re-renders it.
"""

from __future__ import annotations

import os
from importlib import resources
from pathlib import Path

AGENT_NAMES: tuple[str, ...] = ("fr-spec-reviewer", "fr-phase-executor")
"""The agents fr-goal dispatches by name, and so the ones a repo must carry."""

STAMP_KEY = "fr_artifact_version"

AGENTS_DIR = Path(".claude") / "agents"
"""Repo-relative home of the rendered files."""

PINNED_AT_VERSION = 1
"""The `agents` kind's `current_version` when `CANONICAL_SHA256` was taken."""

CANONICAL_SHA256: dict[str, str] = {
    "fr-spec-reviewer": "04111831ebf2ee2b24c8883edb2d147e5c4fa198bc9c1290df705e36afb1ba4f",
    "fr-phase-executor": "319247fc0a1a59d28292d28e61f8cc1b989a53e23c19ec9621d0b6e763b5535a",
}


def canonical_text(name: str) -> str:
    """The canonical agent `name` from the wheel. Raises `KeyError` for a name fr does
    not ship."""
    if name not in AGENT_NAMES:
        raise KeyError(f"{name!r} is not an agent fr ships (fr ships {', '.join(AGENT_NAMES)})")
    return (resources.files(__name__) / f"{name}.md").read_text(encoding="utf-8")


def render_agent(name: str, version: int) -> str:
    """Agent `name` as a repo carries it: the canonical text with `fr_artifact_version:
    <version>` added at the end of its front matter, nothing else changed."""
    from fr.artifacts.registry import set_front_matter_key

    return set_front_matter_key(canonical_text(name), STAMP_KEY, version, append=True)


def agent_path(repo_root: Path, name: str) -> Path:
    return repo_root / AGENTS_DIR / f"{name}.md"


def current_version() -> int:
    from fr.artifacts.registry import ARTIFACT_KINDS

    return ARTIFACT_KINDS["agents"].current_version


def write_agents(repo_root: Path, version: int | None = None) -> list[Path]:
    """Render both agents into `repo_root` at `version` (default: the kind's current
    version), atomically; the paths whose bytes changed. A symlink in their place (how
    this branch first tried it) is replaced by the file, never written through."""
    from fr.artifacts.atomic import write_text_atomic

    v = current_version() if version is None else version
    written: list[Path] = []
    for name in AGENT_NAMES:
        path = agent_path(repo_root, name)
        text = render_agent(name, v)
        if path.is_symlink():
            os.unlink(path)
        elif path.is_file() and path.read_text(encoding="utf-8") == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        fresh = not path.exists()
        write_text_atomic(path, text)
        if fresh:  # a temp file is born 0600; an agent file is an ordinary tracked file
            path.chmod(0o644)
        written.append(path)
    return written


__all__ = [
    "AGENTS_DIR",
    "AGENT_NAMES",
    "CANONICAL_SHA256",
    "PINNED_AT_VERSION",
    "STAMP_KEY",
    "agent_path",
    "canonical_text",
    "current_version",
    "render_agent",
    "write_agents",
]
