"""Repo-collection helpers backing `fr repos sync`.

`fr repos sync` instruments **already-checked-out** repos by writing a
`docs/superpowers/plan-config.yaml` in place — it never clones. This module
holds the pieces with no CLI/typer coupling so they're unit-testable:

- `RepoEntry` / `load_manifest` — the `~/.config/fr/repos.yaml` model.
- `checkout_root` — resolve `owner/repo` to a local path, matching the
  `$FR_REPOS_DIR` / `~/repos/<name>` convention used by
  `fr_dispatch._repo_checkout_root` (kept here, in the base package, so the
  command never reaches across the `fr_dispatch -> fr` layering boundary).
- `render_plan_config` — the per-repo template (the live validator profile
  read by scripts/validate-plans.sh; no dispatch keys).
- `append_to_manifest` — record one-off args durably, idempotently.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

import yaml

DEFAULT_MANIFEST = Path.home() / ".config" / "fr" / "repos.yaml"


class ManifestError(Exception):
    """Raised when the repos manifest is structurally invalid."""


@dataclass(frozen=True)
class RepoEntry:
    """One manifest row: an `owner/name` repo, optionally with an explicit path."""

    repo: str
    path: str | None = None


def load_manifest(path: Path) -> list[RepoEntry]:
    """Parse a repos manifest into `RepoEntry` rows.

    A missing file yields `[]` (the manifest is optional). Accepts plain
    string entries (`owner/name`) and mapping entries (`{repo, path}`);
    unknown mapping keys are ignored. Structural errors raise `ManifestError`.
    """
    if not path.exists():
        return []
    raw = yaml.safe_load(path.read_text()) or {}
    if not isinstance(raw, dict):
        raise ManifestError(f"{path}: top level must be a mapping with a 'repos:' list")
    repos = raw.get("repos", [])
    if repos is None:
        return []
    if not isinstance(repos, list):
        raise ManifestError(f"{path}: 'repos' must be a list")
    out: list[RepoEntry] = []
    for item in repos:
        if isinstance(item, str):
            out.append(RepoEntry(repo=item))
        elif isinstance(item, dict):
            repo = item.get("repo")
            if not isinstance(repo, str):
                raise ManifestError(f"{path}: manifest entry missing a string 'repo' key: {item!r}")
            path_val = item.get("path")
            out.append(RepoEntry(repo=repo, path=path_val if isinstance(path_val, str) else None))
        else:
            raise ManifestError(f"{path}: unsupported manifest entry: {item!r}")
    return out


def checkout_root(entry: RepoEntry, *, repos_dir: Path | None = None) -> Path:
    """Resolve a `RepoEntry` to its local checkout path (no clone).

    Precedence: an explicit per-entry `path`, then the `repos_dir` kwarg, then
    `$FR_REPOS_DIR`, then `~/repos`. The repo's last path segment is the dir
    name — matching `fr_dispatch._repo_checkout_root`.
    """
    if entry.path:
        return Path(entry.path)
    name = entry.repo.split("/")[-1]
    if repos_dir is not None:
        base = repos_dir
    elif os.environ.get("FR_REPOS_DIR"):
        base = Path(os.environ["FR_REPOS_DIR"])
    else:
        base = Path.home() / "repos"
    return base / name


# The validator profile read by scripts/validate-plans.sh — the only keys any
# code reads. No dispatch block, no save_to: those were dead config (removed
# 2026-06-16). The literal `{name}` is the validator's filename placeholder.
_PLAN_CONFIG_TEMPLATE = """\
# Generated by `fr repos sync`. Read by scripts/validate-plans.sh.
plan:
  filename: "YYYY-MM-DD-{name}.md"

header:
  required:
    - Spec
    - Status
  status_values:
    - Not Started
    - In Progress
    - Complete
"""


def render_plan_config() -> str:
    """Render the per-repo `plan-config.yaml` — the live validator profile
    (`plan.filename` + `header.*`) read by `scripts/validate-plans.sh`."""
    return _PLAN_CONFIG_TEMPLATE


def append_to_manifest(path: Path, repo: str) -> bool:
    """Append `repo` to the manifest if absent. Returns True iff appended.

    Creates the file and parent dirs when missing. Idempotent: a repo already
    present (as a string or mapping entry) is not duplicated. The manifest is
    tool-managed — entries are normalized to strings on write.
    """
    existing = load_manifest(path) if path.exists() else []
    if any(e.repo == repo for e in existing):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = [{"repo": e.repo, **({"path": e.path} if e.path else {})} for e in existing]
    normalized: list[object] = [r["repo"] if set(r) == {"repo"} else r for r in rows]
    normalized.append(repo)
    path.write_text(yaml.safe_dump({"repos": normalized}, sort_keys=False))
    return True
